config/routes.rb
CancanDemo::Application.routes.draw do

  devise_for :users

  resources :products
  resources :user do
    resources :products
  end

  root :to => "products#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can [:read, :create], Product
      can :manage, Product, :user_id => user.id
      can :manage, Product, :company => { :user_id => user.id }
      can :destroy, Product, :user_id => user.id, :active => false
      can :manage, Product do |product|
        product.user == user && product.editable?
      end
      can :blowup, :cars
      can :manage, :all
    else
      can :read, Product
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = "Access Denied"
    redirect_to root_url
  end
  
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
  belongs_to :user, :optional => true
  load_and_authorize_resource

  def create
    create! { products_path }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CancanDemo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <% if !user_signed_in? %>
    <%= link_to 'sign up', new_user_registration_path %>
    <%= link_to 'sign in', new_user_session_path %>
  <% else %>
    <%= link_to 'sign out', user_session_path, :method => :delete %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/products/index.html.haml
%h1 Products

- for product in @products do
  = product.name
  = product.price
  - if can? :destroy, product
    = link_to 'destroy', product, :method => :delete
  %br

- if can? :create, Product
  = link_to 'new product', new_user_product_path(current_user)

app/views/products/new.html.haml
%h1 New Product
= semantic_form_for [@user, @product] do |f|
  = f.inputs :name, :price
  = f.buttons